#ifndef AD_CONSTANTS_H
#define AD_CONSTANTS_H

#define INVALID_VEHICLE_ID (-1)
#define EGO_VEHICLE_ID (-2)

#define NUM_VEHICLES_ON_LANE (2)

#define LONGITUDINAL_DIFFERENCE_PERCENTAGE (0.01F)

#define NUM_VEHICLES 6
#define NUM_CYCLES 1000

#endif
